#!/usr/bin/env sh
# convert entire project folders from html to gemini
# vim:fdm=marker

# geminizedir {{{

geminizefile() {
  local file="$1"
  local outFile="$2"

  case "$file" in
    *".html")
      outMod="${outFile%.*}.gmi"
      html2gmi -e -l 0 -i "$file" -o "$outMod"
      echo "converted '${file}' -> '${outMod}'"
      ;;
    # passthrough for non-html files
    *) cp -v "$file" "$outFile" ;;
  esac
}

# }}}

# geminizedir {{{

geminizedir() {
  local dir="$1"
  local outDir="$2"

  mkdir -p "$outDir"

  for file in $(ls -a "$dir"); do
    path="${dir}/${file}"
    outPath="${outDir}/${file}"

    if ! [ "$file" = "." ] && ! [ "$file" = ".." ]; then
      if [ -d "$path" ]; then
        geminizedir "$path" "$outPath"
      else
        geminizefile "$path" "$outPath"
      fi
    fi
  done
}

# }}}

# main {{{

dir="$(pwd)"
[ -d "$1" ] && dir="${dir}/${1%%\/}"

# realpath is an mksh builtin so it's safe
# dir="$(realpath "$dir")"

outDir="${dir}_gemini"

geminizedir "$dir" "$outDir"

echo "done"

# }}}
