#!/usr/bin/env sh
# Gemtext to Markdown converter. Preserves front matter.
# vim:fdm=marker

# linkConvert {{{

linkConvert() {
  local line
  local mark

  line="$(echo "$1" | tr -s "[:space:]" " ")"
  line="${line##=> }"
  line="${line%% }"

  url=$(echo "$line" | cut -d ' ' -f 1)
  alt=$(echo "$line" | cut -d ' ' -f 2-)

  [ -z "$alt" ] && alt="$url"

  case "$url" in
    *.gif|*.jpg|*.jpeg|*.png|*.svg)
      mark="!"
      ;;
  esac

  echo "${mark}[${alt}](${url})"
}

# }}}

# main {{{

inFile="$1"
outFile="$2"

if ! [ -f "$inFile" ] || [ -z "$outFile" ]; then
  echo "USAGE: gmi2md (input gemtext file) (output markdown file)"
  exit 1;
fi

isPreformattedLine=0

IFS=""
while read -r line; do
  case "$line" in
    "\`\`\`"*)
      [ "$isPreformattedLine" = "0" ] && \
        isPreformattedLine=1 || \
        isPreformattedLine=0
      ;;
  esac

  outLine="$line"

  if [ "$isPreformattedLine" = "0" ]; then
    case "$line" in
      "=>"*) outLine="$(linkConvert "$line")\n" ;;
      "#"*) outLine="${line}\n" ;;
      "*"*) outLine="-${line#\*}" ;;
    esac
  fi

  # outData="${outData}$(echo "$outLine" | sed -e 's/\\/\\\\/g')\n"
  outData="${outData}${outLine}\n"
done < "$inFile"

outData="$(echo "$outData" | sed -e 's/\n\n/\n/g')"

echo "$outData" > "$outFile"
echo "converted '${inFile}' -> '${outFile}'"

# }}}
